version: '2'
services:
  prometheus:
    image: 'prom/prometheus:v2.2.1'
    container_name: 'prometheus'
    restart: 'always'
    network_mode: "host"
    volumes:
        - data:/prometheus
        - ./config.yml:/etc/prometheus/prometheus.yml
    environment:
        - METRICS_RESOLUTION:5s
volumes:
    data:
